#ifndef ROBOTICS_ABSTRACTFUNCTIONCALLFROMCONSTRUCTORTEST1_H
#define ROBOTICS_ABSTRACTFUNCTIONCALLFROMCONSTRUCTORTEST1_H
class AbstractFunctionCallFromConstructorTest1{
    AbstractFunctionCallFromConstructorTest1();
    virtual void func(){}
};
#endif //ROBOTICS_ABSTRACTFUNCTIONCALLFROMCONSTRUCTORTEST1_H
