#ifndef ROBOTICS_NOTDEFICIENTENCAPSULATIONTEST_H
#define ROBOTICS_NOTDEFICIENTENCAPSULATIONTEST_H
class NotDeficientEncapsulationTest{
private:
    int f;
};
#endif //ROBOTICS_NOTDEFICIENTENCAPSULATIONTEST_H
