#ifndef ROBOTICS_NOTBROKENMODULARIZATIONTEST1_H
#define ROBOTICS_NOTBROKENMODULARIZATIONTEST1_H
class NotBrokenModularizationTest1 {
    int f1;
    int f2;
    int f3;
};
#endif //ROBOTICS_NOTBROKENMODULARIZATIONTEST1_H
