#ifndef ROBOTICS_NOTGODCLASSTEST1_H
#define ROBOTICS_NOTGODCLASSTEST1_H
class NotGodClassTest1{
    int f1;
    int f2;
    int f3;
    int f4;
    int f5;
    int f6;
    int f7;
    int f8;
    int f9;
    int f10;
    void func1();
    void func2();
    void func3();
    void func4();
    void func5();
    void func6();
    void func7();
    void func8();
};
#endif //ROBOTICS_NOTGODCLASSTEST1_H
