#ifndef ROBOTICS_NOTLONGPARAMETERLISTTEST1_H
#define ROBOTICS_NOTLONGPARAMETERLISTTEST1_H
class NotLongParameterListTest1{
    void func1(int p1, int p2) {}
};
#endif //ROBOTICS_NOTLONGPARAMETERLISTTEST1_H
